// Generated by CoffeeScript 1.7.1
(function() {
  var coffee, concat, gulp, gutil, uglify;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  gutil = require('gulp-util');

  concat = require('gulp-concat');

  uglify = require('gulp-uglify');

  gulp.task('coffee', function() {
    return gulp.src(['index.coffee']).pipe(coffee({
      bare: true
    }).on('error', gutil.log)).pipe(gulp.dest('tmp'));
  });

  gulp.task('concat', function() {
    return gulp.src(['bower_components/phaser/phaser.js', 'tmp/index.js']).pipe(concat('index.min.js')).pipe(uglify()).pipe(gulp.dest('.'));
  });

  gulp.task('default', ['coffee', 'concat']);

}).call(this);
